name: DAST - OWASP ZAP (idor)

on:
  workflow_dispatch:
  push:
    paths:
      - "idor/**"

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start vulnerable app
        working-directory: idor
        run: |
          npm install
          nohup npm start &

      - name: Wait for app to start
        run: sleep 10

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://localhost:3000"
          fail_action: false
